services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx-app
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - netapp
    depends_on:
      - app1
      - app2

  app1:
    container_name: app1
    build:
      context: .
    env_file:
      - .env.production
    environment:
      - RUN_MIGRATIONS=true
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - netapp

  app2:
    container_name: app2
    build:
      context: .
    env_file:
      - .env.production
    environment:
      - RUN_MIGRATIONS=false
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - netapp

  postgres:
    container_name: gobarber-postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/postgresdata
    networks:
      - netapp

  mongodb:
    container_name: mongo-db
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: docker
    volumes:
      - mongo_data:/var/lib/mongodb/mongodata
    networks:
      - netapp

  redis:
    container_name: redis-db
    image: redis:6.2
    command: ['redis-server', '--requirepass', 'docker']
    networks:
      - netapp

networks:
  netapp:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
